### ISSUE TITLE
\f issue for whitespace

### ISSUE THREAD

**Issue by zyntop** [jiaozihan/Liva#2]
In scanner file, when we specify whitespace = [' ' '\t'  '\r' '\n'],  if we inlclude /f, there will be an error message , need to figure out this, if possible, ask TA

**Comment by zyntop** [comment]
correct :  if we inlclude '\f', there will be an error message , need to figure out this, if possible, ask TA

**Comment by zyntop2014** [comment]
consulted with Ta, could delete "\f"
